# Convnet notes

## Prise en compte du stride

Dans le calcul de dx, la prise en compte du stride complexifie grandement les choses. Pour essayer de voir comment les choses se passent, on peut regarder simplement comment est modifié un volume d'entrée élémentaire et on déplacera ensuite la zone d'activation pour cumuler tous les dx.

### Cas d'un vecteur de même dimension que le filtre

$$
x = 
\begin{bmatrix}
x_1\\ 
x_2
\end{bmatrix}
$$

$$
w = 
\begin{bmatrix}
w_1\\ 
w_2
\end{bmatrix}
$$

$$
y = w_1 x_1 + w_2 x_2
$$

$$
dx=\frac{\partial L}{\partial y}\cdot \frac{\partial y}{\partial x}
$$

$$
\begin{align*}
\frac{\partial y}{\partial x}
&=
\begin{bmatrix}
\frac{\partial y}{\partial x_1} & \frac{\partial y}{\partial x_2} 
\end{bmatrix}\\
&=
\begin{bmatrix}
w_1 & w_2
\end{bmatrix}
\end{align*}
$$

$$
\frac{\partial y}{\partial x}
=
\begin{bmatrix}
w_1 & w_2
\end{bmatrix}
$$

### Pad removing

In [8]:
import numpy as np
x = np.random.randn(3,2,2)
x[0]

array([[ 0.30795967, -1.11493902],
       [-0.81509468, -1.11691939]])

In [9]:
pad = 2
x = np.pad(x, ((0,), (pad,), (pad, )), 'constant')
x[0]

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.30795967, -1.11493902,  0.        ,
         0.        ],
       [ 0.        ,  0.        , -0.81509468, -1.11691939,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ]])

In [11]:
x = x[:, pad:-pad, pad:-pad]

In [12]:
x[0]

array([[ 0.30795967, -1.11493902],
       [-0.81509468, -1.11691939]])

In [4]:
cache = []
cache.append(1)
cache.append(9)
cache

[1, 9]

In [6]:
cache[1]

9

In [2]:
import numpy as np

In [4]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [5]:
a.reshape((1, 6, 1, 1))

array([[[[0]],

        [[1]],

        [[2]],

        [[3]],

        [[4]],

        [[5]]]])

In [13]:
x = np.arange(6).reshape((2,3))
x
#group = x[1,:]
#group

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
mean = np.zeros(x.shape)
mean = np.mean(x, axis=1)
mean

array([1., 4.])

In [17]:
a=np.array((2,2,2))
a[:,0:1,:]=[3]

IndexError: too many indices for array