Notes sur les exercices de Stanford CS231n: Convolutional Neural Networks for Visual Recognition

# k-NN

In [2]:
import numpy as np

## Calcul de la matrice des distances L2 (KNN)

In [3]:
xt = np.arange(12.0).reshape((6, 2)) # train

In [4]:
xt

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.]])

In [5]:
x = (np.arange(4.0)*2).reshape((2, 2)) # test
x

array([[0., 2.],
       [4., 6.]])

### Deux boucles

In [ ]:
num_test  = x.shape[0]
num_train = xt.shape[0]
dists = np.zeros((num_test, num_train))
for i in range(num_test):
    for j in range(num_train):
        dists[i,j] = np.sqrt( np.sum( np.square( xt[j] - x[i] ) ) ) 
np.around(dists, decimals=1)

In [6]:
m = np.square(xt-x[0])
m

array([[  0.,   1.],
       [  4.,   1.],
       [ 16.,   9.],
       [ 36.,  25.],
       [ 64.,  49.],
       [100.,  81.]])

In [7]:
v = np.sum( m, axis =1)
v

array([  1.,   5.,  25.,  61., 113., 181.])

In [8]:
np.around(np.sqrt(v), decimals=1)

array([ 1. ,  2.2,  5. ,  7.8, 10.6, 13.5])

### Forme vectorielle: une boucle

In [9]:
for i in range(num_test):
    mat  = np.square( xt - x[i] )
    vect = np.sum( mat, axis=1)
    dists[i] = np.sqrt(vect)
    

np.around(dists, decimals=1)

array([[ 1. ,  2.2,  5. ,  7.8, 10.6, 13.5],
       [ 6.4,  3.6,  1. ,  2.2,  5. ,  7.8]])

### Forme vectorielle: 0 boucle

Déploiement du carré dans L2 et écriture sous forme matricielle

In [10]:
print(x)
print(xt)

[[0. 2.]
 [4. 6.]]
[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]
 [10. 11.]]


In [11]:
np.square(x)

array([[ 0.,  4.],
       [16., 36.]])

In [12]:
x_2 = np.sum(np.square(x), axis = 1)
x_2

array([ 4., 52.])

In [13]:
mx_2 = np.array([x_2,]*num_train)
mx_2

array([[ 4., 52.],
       [ 4., 52.],
       [ 4., 52.],
       [ 4., 52.],
       [ 4., 52.],
       [ 4., 52.]])

In [14]:
xt_2 = np.sum(np.square(xt), axis = 1)
xt_2

array([  1.,  13.,  41.,  85., 145., 221.])

In [15]:
mxt_2 = np.array([xt_2,]*num_test)
mxt_2

array([[  1.,  13.,  41.,  85., 145., 221.],
       [  1.,  13.,  41.,  85., 145., 221.]])

In [16]:
mx_2.T

array([[ 4.,  4.,  4.,  4.,  4.,  4.],
       [52., 52., 52., 52., 52., 52.]])

In [17]:
mp = np.matmul(x,np.transpose(xt))
mp

array([[  2.,   6.,  10.,  14.,  18.,  22.],
       [  6.,  26.,  46.,  66.,  86., 106.]])

In [18]:
m = np.sqrt(mx_2.T+mxt_2 - 2*mp)
np.around(m,decimals=1)

array([[ 1. ,  2.2,  5. ,  7.8, 10.6, 13.5],
       [ 6.4,  3.6,  1. ,  2.2,  5. ,  7.8]])

In [19]:
k_choices = [1, 3, 5, 8, 10, 12, 15, 20, 50, 100]
for k in k_choices:
    print(k)

1
3
5
8
10
12
15
20
50
100


In [20]:
num_folds = 5
for fold in range(num_folds-1):
    print(fold)

0
1
2
3


Folds: segmentation de l'ensemble d'entraînement

In [21]:
xt_folds = np.array_split(xt, 3)

In [22]:
xt_folds

[array([[0., 1.],
        [2., 3.]]), array([[4., 5.],
        [6., 7.]]), array([[ 8.,  9.],
        [10., 11.]])]

In [23]:
np.concatenate((xt_folds[0], xt_folds[1]), axis=0)

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.]])

In [24]:
list_folds = list(range(3))
list_folds

[0, 1, 2]

In [25]:
f = 1
list_folds.remove(f)
list_folds

[0, 2]

In [26]:
for f in list_folds:
    print(f)

0
2


In [27]:
list_folds[1]

2

In [28]:
for c, value in enumerate(xt_folds, 1):
    print(c, value)


1 [[0. 1.]
 [2. 3.]]
2 [[4. 5.]
 [6. 7.]]
3 [[ 8.  9.]
 [10. 11.]]


In [29]:
tuple_test = (1,)
for i in range(4):
    tuple_test = tuple_test + (i,)
tuple_test


(1, 0, 1, 2, 3)

# Linear SVM

In [2]:
import numpy as np

In [26]:
X = np.arange(12.).reshape((4,3))
X

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [31]:
W = np.arange(6.).reshape((3,2))
W

array([[0., 1.],
       [2., 3.],
       [4., 5.]])

Calcul du produit `X[i].dot(W)`

In [32]:
X[0].dot(W)

array([10., 13.])

In [33]:
W[:,1] = 3 * np.arange(3.).reshape(3)
W

array([[0., 0.],
       [2., 3.],
       [4., 6.]])

In [38]:
W+1

array([[1., 1.],
       [3., 4.],
       [5., 7.]])

In [39]:
(W+1) - np.array([[1,2,3],]*2).T

array([[0., 0.],
       [1., 2.],
       [2., 4.]])

In [3]:
np.array([[1,2,3],]*2)

array([[1, 2, 3],
       [1, 2, 3]])

In [4]:
np.array([[1,2,3],]*2).T

array([[1, 1],
       [2, 2],
       [3, 3]])

In [41]:
a = np.array([1, 0, 3])
b = np.zeros((3, 4))
b[np.arange(3), a] = 1
b

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [42]:
1-b

array([[1., 0., 1., 1.],
       [0., 1., 1., 1.],
       [1., 1., 1., 0.]])

In [43]:
x1 = np.arange(9.0).reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [45]:
x2 = np.arange(3.0)
x2

array([0., 1., 2.])

In [47]:
np.multiply(x1, x1)

array([[ 0.,  1.,  4.],
       [ 9., 16., 25.],
       [36., 49., 64.]])

##     Structured SVM loss function, vectorized implementation.

Création d'un jeu d'essai simplifié pour les tests:

In [14]:
import numpy as np

X = np.array([[1,2,3],
              [2,1,3],
              [1,2,1],
              [3,2,1],
              [1,3,2]])
y = np.array([1,0,3,1,2])

W = np.random.randn(3, 4) * 0.0001 
delta = 1.0
num_classes = W.shape[1] # C
num_train   = X.shape[0] # N
num_dim     = X.shape[1] # D

print('C = ', num_classes)
print('N = ', num_train)
print('D = ', num_dim)

C =  4
N =  5
D =  3


In [15]:
from cs231n.classifiers.linear_svm import svm_loss_naive
loss, grad = svm_loss_naive(W, X, y, 0.0)
loss

2.9994442637540955

In [16]:
scores = np.matmul(X,W) # Matrice N,C
scores

array([[ 1.03068749e-04, -2.01816660e-04,  1.79131403e-04,
        -1.02641386e-03],
       [ 1.46188071e-04, -1.47367594e-04,  2.16528938e-04,
        -1.11381069e-03],
       [-1.75098827e-04, -6.11461641e-05,  7.39151241e-05,
        -5.57830351e-04],
       [-3.27061475e-04,  1.75786467e-05,  1.37983160e-04,
        -8.90051855e-04],
       [-1.55115684e-04, -1.46568073e-04,  1.21159747e-04,
        -8.70836028e-04]])

In [17]:
y_one_hot = np.zeros((y.size, num_classes))
y_one_hot[np.arange(y.size),y] = 1 # Matrice N,C
y_one_hot

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [18]:
correct_class_score = np.sum(np.multiply(scores, y_one_hot), axis=1)
correct_class_score

array([-2.01816660e-04,  1.46188071e-04, -5.57830351e-04,  1.75786467e-05,
        1.21159747e-04])

In [19]:
np.array([correct_class_score,]*num_classes).T

array([[-2.01816660e-04, -2.01816660e-04, -2.01816660e-04,
        -2.01816660e-04],
       [ 1.46188071e-04,  1.46188071e-04,  1.46188071e-04,
         1.46188071e-04],
       [-5.57830351e-04, -5.57830351e-04, -5.57830351e-04,
        -5.57830351e-04],
       [ 1.75786467e-05,  1.75786467e-05,  1.75786467e-05,
         1.75786467e-05],
       [ 1.21159747e-04,  1.21159747e-04,  1.21159747e-04,
         1.21159747e-04]])

In [20]:
margins = scores - np.array([correct_class_score,]*num_classes).T + delta

In [21]:
np.maximum(0, margins) 


array([[1.00030489, 1.        , 1.00038095, 0.9991754 ],
       [1.        , 0.99970644, 1.00007034, 0.99874   ],
       [1.00038273, 1.00049668, 1.00063175, 1.        ],
       [0.99965536, 1.        , 1.0001204 , 0.99909237],
       [0.99972372, 0.99973227, 1.        , 0.999008  ]])

In [22]:
margins = np.maximum(0, margins) 


In [23]:
margins = np.multiply(margins, (1-y_one_hot))
margins

array([[1.00030489, 0.        , 1.00038095, 0.9991754 ],
       [0.        , 0.99970644, 1.00007034, 0.99874   ],
       [1.00038273, 1.00049668, 1.00063175, 0.        ],
       [0.99965536, 0.        , 1.0001204 , 0.99909237],
       [0.99972372, 0.99973227, 0.        , 0.999008  ]])

In [24]:
loss = np.sum(margins) /num_train


In [25]:
loss

2.9994442637540955

## Calcul du gradient - forme vectorisée

In [78]:
import numpy as np

In [26]:
#margins[0,0] = -1
margins

array([[1.00030489, 0.        , 1.00038095, 0.9991754 ],
       [0.        , 0.99970644, 1.00007034, 0.99874   ],
       [1.00038273, 1.00049668, 1.00063175, 0.        ],
       [0.99965536, 0.        , 1.0001204 , 0.99909237],
       [0.99972372, 0.99973227, 0.        , 0.999008  ]])

In [27]:
margins>0

array([[ True, False,  True,  True],
       [False,  True,  True,  True],
       [ True,  True,  True, False],
       [ True, False,  True,  True],
       [ True,  True, False,  True]])

In [28]:
np.sum(margins>0, axis=1)

array([3, 3, 3, 3, 3])

In [29]:
1*(margins>0)

array([[1, 0, 1, 1],
       [0, 1, 1, 1],
       [1, 1, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 0, 1]])

In [30]:
np.multiply(y_one_hot, - np.array([np.sum(margins>0, axis=1),]*num_classes).T    )

array([[-0., -3., -0., -0.],
       [-3., -0., -0., -0.],
       [-0., -0., -0., -3.],
       [-0., -3., -0., -0.],
       [-0., -0., -3., -0.]])

In [31]:
y_one_hot

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [32]:
s_grad = 1*(margins>0) + np.multiply(y_one_hot, - np.array([np.sum(margins>0, axis=1),]*num_classes).T    )

In [33]:
s_grad

array([[ 1., -3.,  1.,  1.],
       [-3.,  1.,  1.,  1.],
       [ 1.,  1.,  1., -3.],
       [ 1., -3.,  1.,  1.],
       [ 1.,  1., -3.,  1.]])

In [91]:
X[0]

array([1, 2, 3])

In [92]:
s_grad[0]

array([ 0., -2.,  1.,  1.])

In [93]:
dW0 = np.outer(X[0], s_grad[0])
dW0

array([[ 0., -2.,  1.,  1.],
       [ 0., -4.,  2.,  2.],
       [ 0., -6.,  3.,  3.]])

In [98]:
dW1 = np.outer(X[0], s_grad[1])
dW1

array([[-3.,  1.,  1.,  1.],
       [-6.,  2.,  2.,  2.],
       [-9.,  3.,  3.,  3.]])

In [94]:
dW0.shape

(3, 4)

In [95]:
X

array([[1, 2, 3],
       [2, 1, 3],
       [3, 2, 1],
       [1, 3, 2]])

In [35]:
s_grad.shape

(5, 4)

In [34]:
X.shape

(5, 3)

In [37]:
dW = np.matmul(X.T, s_grad)

In [38]:
dW /= num_train

In [39]:
dW

array([[ 0. , -1.6,  0.8,  0.8],
       [ 1.2, -1.2, -0.4,  0.4],
       [-0.4, -1.2,  0.4,  1.2]])

In [40]:
grad

array([[ 0. , -1.6,  0.8,  0.8],
       [ 1.2, -1.2, -0.4,  0.4],
       [-0.4, -1.2,  0.4,  1.2]])

In [53]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A.shape

(2, 3)

In [54]:
B = np.array([[1, 2, 3, 4]])
B.shape

(1, 4)

In [55]:
C = np.multiply.outer(A, B)
C.shape; C

array([[[[ 1,  2,  3,  4]],

        [[ 2,  4,  6,  8]],

        [[ 3,  6,  9, 12]]],


       [[[ 4,  8, 12, 16]],

        [[ 5, 10, 15, 20]],

        [[ 6, 12, 18, 24]]]])

In [58]:
dW0 = np.multiply.outer(s_grad,X)


In [60]:
dW0.shape

(4, 4, 4, 3)

## Stochastic Gradient Descent

In [1]:
import numpy as np

In [18]:
batch_size = 2 
num_train  = 5
indices = np.random.choice(num_train, batch_size)

In [19]:
indices

array([0, 0])

In [20]:
for counter, value in enumerate(indices):
    print(counter, value)

0 0
1 0


In [21]:
dim = 3
X_batch = np.zeros((batch_size, dim))
X_batch

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
for counter, value in enumerate(indices):
    X_batch[counter] = X[value]

In [23]:
X_batch

array([[1., 2., 3.],
       [1., 2., 3.]])

In [24]:
X

array([[1, 2, 3],
       [2, 1, 3],
       [1, 2, 1],
       [3, 2, 1],
       [1, 3, 2]])

In [9]:
X = np.array([[1,2,3],
              [2,1,3],
              [1,2,1],
              [3,2,1],
              [1,3,2]])
y = np.array([1,0,3,1,2])

W = np.random.randn(3, 4) * 0.0001 
delta = 1.0
num_classes = W.shape[1] # C
num_train   = X.shape[0] # N
dim         = X.shape[1] # D

print('C = ', num_classes)
print('N = ', num_train)
print('D = ', dim)

C =  4
N =  5
D =  3


In [10]:
from cs231n.classifiers.linear_svm import svm_loss_vectorized
from cs231n.classifiers.linear_svm import svm_loss_naive

loss_vectorized, grad_vectorized = svm_loss_vectorized(W, X, y, 0.0)
grad_vectorized

array([[ 0. , -1.6,  0.8,  0.8],
       [ 1.2, -1.2, -0.4,  0.4],
       [-0.4, -1.2,  0.4,  1.2]])

In [11]:
loss_vectorized

2.999663322546778

In [12]:
loss_naive, grad_naive = svm_loss_naive(W, X, y, 0.0)
grad_naive

array([[ 0. , -1.6,  0.8,  0.8],
       [ 1.2, -1.2, -0.4,  0.4],
       [-0.4, -1.2,  0.4,  1.2]])

In [13]:
loss_naive

2.999663322546778

In [14]:
batch_size = 2
X_batch = np.zeros((batch_size, dim))
y_batch = np.zeros((batch_size,))
indices = np.random.choice(num_train, batch_size)
for counter, value in enumerate(indices):
    X_batch[counter] = X[value]
    y_batch[counter] = y[value]

In [15]:
loss_naive, grad_naive = svm_loss_naive(W, X_batch, y_batch, 0.0)


In [16]:
grad_naive

array([[-2.5,  1.5, -0.5,  1.5],
       [ 0. ,  2. , -4. ,  2. ],
       [-3.5,  2.5, -1.5,  2.5]])

In [17]:
loss_vectorized, grad_vectorized = svm_loss_vectorized(W, X_batch, y_batch, 0.0)
grad_vectorized

array([[-2.5,  1.5, -0.5,  1.5],
       [ 0. ,  2. , -4. ,  2. ],
       [-3.5,  2.5, -1.5,  2.5]])

# Softmax exercice

In [2]:
import numpy as np

In [3]:
#logits = np.matmul(X,W)
logits = np.array([[1,2,3],
                   [2,1,4]])
C = np.max(logits, axis=1)
C

array([3, 4])

In [4]:
logits = logits - np.array([C,]*3).T
logits

array([[-2, -1,  0],
       [-2, -3,  0]])

In [6]:
y_1_hot = np.array([[0,1,0],
                    [1,0,0]])
np.multiply(y_1_hot, logits)

array([[ 0, -1,  0],
       [-2,  0,  0]])

In [7]:
np.sum(np.multiply(y_1_hot, logits), axis=1)

array([-1, -2])

In [9]:
np.log(np.sum(np.exp(logits), axis=1))

array([0.40760596, 0.16984602])

In [10]:
X = np.array([[1,2,3],
              [2,1,3],
              [1,2,1],
              [3,2,1],
              [1,3,2]])
y = np.array([1,0,3,1,2])

W = np.random.randn(3, 4) * 0.0001 
delta = 1.0
num_classes = W.shape[1] # C
num_train   = X.shape[0] # N
dim         = X.shape[1] # D

print('C = ', num_classes)
print('N = ', num_train)
print('D = ', dim)

C =  4
N =  5
D =  3


In [15]:
logits = np.matmul(X,W)

In [16]:
logits - np.array([np.max(logits, axis=1),] * num_classes).T

array([[-2.76396034e-04,  0.00000000e+00, -8.27623858e-04,
        -1.62236696e-04],
       [ 0.00000000e+00, -1.63152547e-04, -8.54128478e-04,
        -1.24998371e-04],
       [-3.45152679e-04,  0.00000000e+00, -5.81496716e-04,
        -3.47676465e-04],
       [-1.21085734e-05,  0.00000000e+00, -7.04921578e-04,
        -3.74086202e-04],
       [-5.83800884e-04,  0.00000000e+00, -9.02920644e-04,
        -4.68552321e-04]])